export const UF_LABEL = [
  { nome: "Acre" },
  { sigla: "AC" },
  { nome: "Alagoas" },
  { sigla: "AL" },
  { nome: "Amapá" },
  { sigla: "AP" },
  { nome: "Amazonas" },
  { sigla: "AM" },
  { nome: "Bahia" },
  { sigla: "BA" },
  { nome: "Ceará" },
  { sigla: "CE" },
  { nome: "Distrito Federal" },
  { sigla: "DF" },
  { nome: "Espírito Santo" },
  { sigla: "ES" },
  { nome: "Goiás" },
  { sigla: "GO" },
  { nome: "Maranhão" },
  { sigla: "MA" },
  { nome: "Mato Grosso" },
  { sigla: "MT" },
  { nome: "Mato Grosso do Sul" },
  { sigla: "MS" },
  { nome: "Minas Gerais" },
  { sigla: "MG" },
  { nome: "Pará" },
  { sigla: "PA" },
  { nome: "Paraíba" },
  { sigla: "PB" },
  { nome: "Paraná" },
  { sigla: "PR" },
  { nome: "Pernambuco" },
  { sigla: "PE" },
  { nome: "Piauí" },
  { sigla: "PI" },
  { nome: "Rio de Janeiro" },
  { sigla: "RJ" },
  { nome: "Rio Grande do Norte" },
  { sigla: "RN" },
  { nome: "Rio Grande do Sul" },
  { sigla: "RS" },
  { nome: "Rondônia" },
  { sigla: "RO" },
  { nome: "Roraima" },
  { sigla: "RR" },
  { nome: "Santa Catarina" },
  { sigla: "SC" },
  { nome: "São Paulo" },
  { sigla: "SP" },
  { nome: "Sergipe" },
  { sigla: "SE" },
  { nome: "Tocantins" },
  { sigla: "TO" },
];

export const DOCUMENT_STATUS = [
  "Regular",
  "Renovar",
  "Vencida",
  "Dispensada",
  "Renovada",
  "Em Renovacao",
  "COVID",
];

export const ACCOUNTABLE = [{ nome: "Interno" }, { nome: "Provedor" }];

export const DOCUMENT_TYPE = [
  { nome: "Habite-se - Termo de Conclusão de Obra" },
  { nome: "AVCB - Alvará do Corpo de Bombeiros" },
  { nome: "Licença de Funcionamento da Prefeitura" },
  { nome: "Licença Ambiental de Operação" },
  { nome: "Alvará Sanitário" },
  { nome: "Outorga de Perfuração" },
  { nome: "CREA" },
  { nome: "CRQ" },
  { nome: "LICENÇA EXERCITO" },
  { nome: "CREMEPE" },
  { nome: "AMBIENTAL - LI" },
  { nome: "LICENÇA PF" },
  { nome: "AMBIENTAL - LP" },

  { nome: "Alvará de Funcionamento (Prefeitura)" },
  { nome: "Alvará Sanitário de Estabelecimento" },
  { nome: "Alvará Sanitário de Veículos" },
  { nome: "AVCB - Auto de Vistoria do Corpo de Bombeiros" },
  { nome: "AVCB - Responsável Técnico" },
  { nome: "CA - Certificado de Autorização do Corpo de Bombeiros" },
  { nome: "CADRI - Certificado de Movimentação de Resíduos Ambientais" },
  { nome: "CLI - Certificado de Licenciamento Integrado" },
  { nome: "COREN - Conselho Regional de Enfermagem" },
  { nome: "CREA - Conselho Regional de Engenharia e Agronomia" },
  { nome: "CREA - Responsável Técnico" },
  { nome: "CRM - Conselho Regional de Medicina" },
  { nome: "CRQ - Conselho Regional de Químicos" },
  { nome: "CRQ - Responsável Técnico" },
  { nome: "Exército - Certificado de Produtos Controlados" },
  { nome: "Habite-se (Termo de Conclusão de Obra)" },
  { nome: "IBAMA - Cadastro Técnico Federal (CTF)" },
  { nome: "LO - Licença de Operação Ambiental (Estadual)" },
  { nome: "LO - Licença de Operação Ambiental (Federal)" },
  { nome: "LO - Licença de Operação Ambiental (Municipal)" },
  { nome: "Outorga de Perfuração" },
  { nome: "Polícia Civil - Certificado de Produtos Controlados" },
  { nome: "Polícia Federal - Certificado de Produtos Controlados" },

  { nome: "Outros" },
];
